### Service Document
GET http://localhost:4004/client

### Service $metadata document
GET http://localhost:4004/client/$metadata

### Browsing Books
GET http://localhost:4004/client/Jobs?$expand=steps

### Browsing Authors
GET http://localhost:4004/client/JobStep?
# &$select=name,dateOfBirth,placeOfBirth
# &$expand=books($select=title;$expand=currency)
# &$filter=ID eq 101
# &sap-language=de
